#!/usr/bin/env node
// Build the qualitative pilot from manifests/pilot/*.json:
//   pilot/cells.json         every architecture x rung, with its neutral code
//   pilot/PLAYS.md           Tier A and Tier B plays across the three harnesses
//   pilot/bootstraps/P-NN.md one bootstrap per cell
// Usage: node tools/pilot.js          write everything
//        node tools/pilot.js --check  fail if committed files are stale
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { assembleBootstrap, prefaceLeaks } from './lib/bootstrap.js';
import { validateManifest } from './lib/manifest.js';
import { PILOT_SEED, planPilot } from './lib/pilot.js';
import { loadVocabulary, repoRoot } from './lib/vocabulary.js';

const check = process.argv.includes('--check');
const at = rel => new URL(rel, repoRoot);
const vocab = loadVocabulary();

const entries = readdirSync(at('manifests/pilot/')).filter(n => n.endsWith('.json')).sort().map(name => {
  const manifest = JSON.parse(readFileSync(at(`manifests/pilot/${name}`), 'utf8'));
  const { errors } = validateManifest(manifest, vocab);
  if (errors.length) throw new Error(`manifests/pilot/${name} is invalid:\n  ${errors.join('\n  ')}`);
  return { slug: name.replace(/\.json$/, ''), manifest };
});

const { cells, plays } = planPilot(entries, vocab);
const manifestOf = slug => entries.find(e => e.slug === slug).manifest;

const outputs = new Map();
outputs.set('pilot/cells.json', `${JSON.stringify({
  seed: PILOT_SEED,
  note: 'Spoilers: each code maps to a manifest and rung. Testers should receive only the bootstrap file for their code.',
  cells: cells.map(c => ({ code: c.code, group: c.group, rung: c.rung, manifest: `manifests/pilot/${c.slug}.json` })),
}, null, 2)}\n`);

for (const cell of cells) {
  const manifest = manifestOf(cell.slug);
  const text = assembleBootstrap(manifest, { rung: cell.rung, label: cell.code, vocab });
  const leaks = prefaceLeaks(text, manifest, vocab);
  if (leaks.length) throw new Error(`${cell.code}: sealed material before the divider: ${leaks.join('; ')}`);
  outputs.set(`pilot/bootstraps/${cell.code}.md`, text);
}

outputs.set('pilot/PLAYS.md', [
  '# Pilot plays',
  '',
  'Generated by `node tools/pilot.js`. Do not edit by hand.',
  '',
  '- **Tier A** plays every Invariants / Secrets cell in all three harnesses. **Tier B** plays the thinner cells once each, rotated so every architecture meets all three harnesses.',
  '- Give a tester only the bootstrap file for their play, and tell them which harness to use. Don\'t tell them anything else about the cell.',
  '- **Never give one tester two plays from the same group.** A group is one architecture; a second play would already be spoiled.',
  '- Track who took which play privately, outside this repository.',
  '',
  '| Play | Bootstrap | Harness | Tier | Group |',
  '|---|---|---|---|---|',
  ...plays.map(p => `| ${p.play} | [${p.code}](bootstraps/${p.code}.md) | ${p.harness} | ${p.tier} | ${p.group} |`),
  '',
].join('\n'));

if (check) {
  const stale = [...outputs].filter(([rel, text]) => !existsSync(at(rel)) || readFileSync(at(rel), 'utf8') !== text).map(([rel]) => rel);
  const expected = new Set([...outputs.keys()].filter(k => k.startsWith('pilot/bootstraps/')).map(k => k.split('/').pop()));
  const extra = existsSync(at('pilot/bootstraps/'))
    ? readdirSync(at('pilot/bootstraps/')).filter(n => !expected.has(n)).map(n => `pilot/bootstraps/${n}`)
    : [];
  if (stale.length || extra.length) {
    console.error(`Pilot files are out of date; run node tools/pilot.js\n  ${[...stale, ...extra].join('\n  ')}`);
    process.exit(1);
  }
  console.log(`Pilot files are current: ${cells.length} cells, ${plays.length} plays.`);
} else {
  rmSync(at('pilot/bootstraps/'), { recursive: true, force: true });
  mkdirSync(at('pilot/bootstraps/'), { recursive: true });
  for (const [rel, text] of outputs) writeFileSync(at(rel), text);
  console.log(`Wrote ${cells.length} bootstraps and ${plays.length} plays.`);
}
